apiVersion: aadpodidentity.k8s.io/v1
kind: AzureIdentity
metadata:
  name: vault
  namespace: vault
spec:
  type: 0
  ResourceID: "${vault_aad_resource_id}"
  ClientID: "${vault_aad_client_id}"
---
apiVersion: aadpodidentity.k8s.io/v1
kind: AzureIdentityBinding
metadata:
  name: vault
  namespace: vault
spec:
  AzureIdentity: vault
  Selector: vault
