apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: wildcard
  namespace: istio-system
  labels:
    use-azuredns-solver: 'true'
spec:
  secretName: wildcard-tls
  commonName: "*.${ ingress_domain }"
  dnsNames:
  - "*.${ ingress_domain }"
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
